-- PERSON
-- 5 Personen für Angestellte (PERSON_ID 1..5)
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT, TELEFON, EMAIL)
VALUES (1, 'Anna', 'Müller', TO_DATE('1985-04-12','YYYY-MM-DD'), 'W', '+49-170-1111111', 'anna.mueller@example.de');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT, TELEFON, EMAIL)
VALUES (2, 'Jens', 'Becker', TO_DATE('1978-09-30','YYYY-MM-DD'), 'M', '+49-170-2222222', 'jens.becker@example.de');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT, TELEFON, EMAIL)
VALUES (3, 'Maria', 'Schmidt', TO_DATE('1992-01-20','YYYY-MM-DD'), 'W', '+49-170-3333333', 'maria.schmidt@example.de');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT, TELEFON, EMAIL)
VALUES (4, 'Tom', 'Klein', TO_DATE('1990-07-01','YYYY-MM-DD'), 'M', '+49-170-4444444', 'tom.klein@example.de');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT, TELEFON, EMAIL)
VALUES (5, 'Alex', 'König', TO_DATE('1975-01-15','YYYY-MM-DD'), 'D', '+49-170-9988776', 'alex.koenig@example.de');

-- 5 Personen für Gefangene (PERSON_ID 6..10)
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT)
VALUES (6, 'Thomas', 'Klein', TO_DATE('1988-02-14','YYYY-MM-DD'), 'M');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT)
VALUES (7, 'Arda', 'Yilmaz', TO_DATE('1990-09-10','YYYY-MM-DD'), 'M');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT)
VALUES (8, 'Lukas', 'Bauer', TO_DATE('1995-11-02','YYYY-MM-DD'), 'M');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT)
VALUES (9, 'Marco', 'Rossi', TO_DATE('1982-06-21','YYYY-MM-DD'), 'M');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT)
VALUES (10, 'Peter', 'Schulz', TO_DATE('1979-12-05','YYYY-MM-DD'), 'M');

-- 6 Personen für Besucher (PERSON_ID 11..16), davon 3 Anwälte
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT, TELEFON, EMAIL)
VALUES (11, 'Laura', 'Fischer', TO_DATE('1987-08-18','YYYY-MM-DD'), 'W', '+49-170-5550001', 'laura.fischer@example.de');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT, TELEFON, EMAIL)
VALUES (12, 'Mark', 'Weber', TO_DATE('1984-12-05','YYYY-MM-DD'), 'M', '+49-170-5550002', 'mark.weber@example.de');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT, TELEFON, EMAIL)
VALUES (13, 'Sophie', 'Neumann', TO_DATE('1991-03-22','YYYY-MM-DD'), 'W', '+49-170-5550003', 'sophie.neumann@example.de');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT, TELEFON, EMAIL)
VALUES (14, 'Dr. Max', 'Recht', TO_DATE('1970-05-10','YYYY-MM-DD'), 'M', '+49-170-5551001', 'max.recht@kanzlei.de');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT, TELEFON, EMAIL)
VALUES (15, 'Eva', 'Jurist', TO_DATE('1975-09-30','YYYY-MM-DD'), 'W', '+49-170-5551002', 'eva.jurist@kanzlei.de');
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSDATUM, GESCHLECHT, TELEFON, EMAIL)
VALUES (16, 'Paul', 'Advokat', TO_DATE('1968-02-02','YYYY-MM-DD'), 'M', '+49-170-5551003', 'paul.advokat@kanzlei.de');

-- STANDORT
INSERT INTO STANDORT(STANDORT_ID, NAME, STRASSE, PLZ, ORT) VALUES (1, 'JVA Berlin', 'Friedrichstraße', '10115', 'Berlin');
INSERT INTO STANDORT(STANDORT_ID, NAME, STRASSE, PLZ, ORT) VALUES (2, 'JVA Minden', 'Ringstraße', '32423', 'Minden');

-- ANGESTELLTER
-- ANGESTELLTER_IDs explizit gesetzt, VORGESETZTEN_ID referenziert vorhandene ANGESTELLTER
INSERT INTO ANGESTELLTER (ANGESTELLTER_ID, PERSON_ID, ROLLE, EINSTELLUNGSDATUM, STRASSE, PLZ, ORT, VORGESETZTEN_ID, AUSTRITTSDATUM, STANDORT_ID, ABTEILUNG)
VALUES (4101, 1, 'Leiter Verwaltung', TO_DATE('2010-02-01','YYYY-MM-DD'), 'Hauptstr. 1', '32139', 'Spenge', NULL, NULL, 1, 'Verwaltung');
INSERT INTO ANGESTELLTER (ANGESTELLTER_ID, PERSON_ID, ROLLE, EINSTELLUNGSDATUM, STRASSE, PLZ, ORT, VORGESETZTEN_ID, AUSTRITTSDATUM, STANDORT_ID, ABTEILUNG)
VALUES (4102, 2, 'Werkstattleiter', TO_DATE('2015-03-15','YYYY-MM-DD'), 'Am Hafen 3', '28195', 'Bremen', 4101, NULL, 2, 'Werkstatt');
INSERT INTO ANGESTELLTER (ANGESTELLTER_ID, PERSON_ID, ROLLE, EINSTELLUNGSDATUM, STRASSE, PLZ, ORT, VORGESETZTEN_ID, AUSTRITTSDATUM, STANDORT_ID, ABTEILUNG)
VALUES (4103, 3, 'Lageristin', TO_DATE('2023-09-01','YYYY-MM-DD'), 'Lagerweg 2', '48143', 'Münster', 4102, TO_DATE('2025-05-01','YYYY-MM-DD'), 1, 'Lager');
INSERT INTO ANGESTELLTER (ANGESTELLTER_ID, PERSON_ID, ROLLE, EINSTELLUNGSDATUM, STRASSE, PLZ, ORT, VORGESETZTEN_ID, AUSTRITTSDATUM, STANDORT_ID, ABTEILUNG)
VALUES (4104, 4, 'IT-Administrator', TO_DATE('2018-01-10','YYYY-MM-DD'), 'Netzweg 5', '32139', 'Spenge', 4101, NULL, 1, 'IT');
INSERT INTO ANGESTELLTER (ANGESTELLTER_ID, PERSON_ID, ROLLE, EINSTELLUNGSDATUM, STRASSE, PLZ, ORT, VORGESETZTEN_ID, AUSTRITTSDATUM, STANDORT_ID, ABTEILUNG)
VALUES (4105, 5, 'Personalreferent', TO_DATE('2019-04-20','YYYY-MM-DD'), 'Musterstr. 9', '32423', 'Minden', 4101, NULL, 2, 'Personal');

-- LIEFERANT
INSERT INTO LIEFERANT (LIEFERANT_ID, NAME, TYP, STRASSE, PLZ, ORT, TELEFON, EMAIL, STATUS)
VALUES (1001, 'NordMed GmbH', 'Medizin', 'Hafenstraße 12', '28195', 'Bremen', '+49-421-600000', 'kontakt@nordmed.de', 'aktiv');

INSERT INTO LIEFERANT (LIEFERANT_ID, NAME, TYP, STRASSE, PLZ, ORT, TELEFON, EMAIL, STATUS)
VALUES (1002, 'BauProfi AG', 'Baustoff', 'Industriestr. 4', '30159', 'Hannover', '+49-511-700000', 'info@bauprofi.de', 'aktiv');

INSERT INTO LIEFERANT (LIEFERANT_ID, NAME, TYP, STRASSE, PLZ, ORT, TELEFON, EMAIL, STATUS)
VALUES (1003, 'FoodSupply KG', 'Lebensmittel', 'Marktweg 7', '48143', 'Münster', '+49-251-800000', 'sales@foodsupply.de', 'aktiv');

INSERT INTO LIEFERANT (LIEFERANT_ID, NAME, TYP, STRASSE, PLZ, ORT, TELEFON, EMAIL, STATUS)
VALUES (1004, 'TechParts GmbH', 'Technik', 'Werkstr. 8', '32423', 'Minden', '+49-571-123456', 'sales@techparts.de', 'aktiv');

INSERT INTO LIEFERANT (LIEFERANT_ID, NAME, TYP, STRASSE, PLZ, ORT, TELEFON, EMAIL, STATUS)
VALUES (1005, 'CleanServ GmbH', 'Dienstleistung', 'Reinweg 3', '10115', 'Berlin', '+49-30-444555', 'kontakt@cleanserv.de', 'inaktiv');

INSERT INTO LIEFERANT (LIEFERANT_ID, NAME, TYP, STRASSE, PLZ, ORT, TELEFON, EMAIL, STATUS)
VALUES (1006, 'OfficeSupply OHG', 'Bürobedarf', 'Büroallee 2', '32423', 'Minden', '+49-571-654321', 'orders@officesupply.de', 'aktiv');

-- ARTIKEL
INSERT INTO ARTIKEL (ARTIKEL_ID, BEZEICHNUNG, KATEGORIE, EINHEIT, BEMERKUNG)
VALUES (3001, 'Verbandkasten Standard', 'Medizin', 'Stück', 'Erste Hilfe, geprüft');

INSERT INTO ARTIKEL (ARTIKEL_ID, BEZEICHNUNG, KATEGORIE, EINHEIT, BEMERKUNG)
VALUES (3002, 'Zement 25kg', 'Baustoff', 'Sack', 'Portlandzement');

INSERT INTO ARTIKEL (ARTIKEL_ID, BEZEICHNUNG, KATEGORIE, EINHEIT, BEMERKUNG)
VALUES (3003, 'Generator 5kW', 'Technik', 'Stück', 'Notstromaggregat');

INSERT INTO ARTIKEL (ARTIKEL_ID, BEZEICHNUNG, KATEGORIE, EINHEIT, BEMERKUNG)
VALUES (3004, 'OP‑Masken (Box 50)', 'Medizin', 'Box', 'Einweg, EN14683');

INSERT INTO ARTIKEL (ARTIKEL_ID, BEZEICHNUNG, KATEGORIE, EINHEIT, BEMERKUNG)
VALUES (3005, 'Schrauben Sortiment', 'Technik', 'Set', 'verschiedene Größen');

INSERT INTO ARTIKEL (ARTIKEL_ID, BEZEICHNUNG, KATEGORIE, EINHEIT, BEMERKUNG)
VALUES (3006, 'Kantinen‑Tiefkühlkost Pack', 'Lebensmittel', 'Palette', 'Tiefkühl, 200 Portionen');

INSERT INTO ARTIKEL (ARTIKEL_ID, BEZEICHNUNG, KATEGORIE, EINHEIT, BEMERKUNG)
VALUES (3007, 'Reinigungsmittel 10L', 'Dienstleistung', 'Kanister', 'Konzentrat');

INSERT INTO ARTIKEL (ARTIKEL_ID, BEZEICHNUNG, KATEGORIE, EINHEIT, BEMERKUNG)
VALUES (3008, 'Büro‑Papier A4 5000 Blatt', 'Bürobedarf', 'Pack', '80g/m2'); 

-- LIEFERUNG
INSERT INTO LIEFERUNG (LIEFERUNG_ID, LIEFERANT_ID, STANDORT_ID, LIEFERDATUM, STATUS)
VALUES (5001, 1001, 1, TO_TIMESTAMP('2025-11-10 09:30:00','YYYY-MM-DD HH24:MI:SS'), 'abgeschlossen');

INSERT INTO LIEFERUNG (LIEFERUNG_ID, LIEFERANT_ID, STANDORT_ID, LIEFERDATUM, STATUS)
VALUES (5002, 1002, 2, TO_TIMESTAMP('2025-12-01 14:15:00','YYYY-MM-DD HH24:MI:SS'), 'in_bearbeitung');

INSERT INTO LIEFERUNG (LIEFERUNG_ID, LIEFERANT_ID, STANDORT_ID, LIEFERDATUM, STATUS)
VALUES (5003, 1003, 1, TO_TIMESTAMP('2025-12-05 08:00:00','YYYY-MM-DD HH24:MI:SS'), 'geplant');

INSERT INTO LIEFERUNG (LIEFERUNG_ID, LIEFERANT_ID, STANDORT_ID, LIEFERDATUM, STATUS)
VALUES (5004, 1002, 1, TO_TIMESTAMP('2025-10-20 07:45:00','YYYY-MM-DD HH24:MI:SS'), 'storniert');

INSERT INTO LIEFERUNG (LIEFERUNG_ID, LIEFERANT_ID, STANDORT_ID, LIEFERDATUM, STATUS)
VALUES (5005, 1001, 2, TO_TIMESTAMP('2025-12-15 16:00:00','YYYY-MM-DD HH24:MI:SS'), 'teilweise');

-- LIEFERPOSITION
-- Annahme: LIEFERUNG 5001 von LIEFERANT 1001 (NordMed GmbH - Medizin)
INSERT INTO LIEFERPOSITION (LIEFERPOSITION_ID, LIEFERUNG_ID, ARTIKEL_ID, MENGE, EINZELPREIS, BEMERKUNG)
VALUES (7001, 5001, 3001, 50, 12.50, 'geliefert');
INSERT INTO LIEFERPOSITION (LIEFERPOSITION_ID, LIEFERUNG_ID, ARTIKEL_ID, MENGE, EINZELPREIS, BEMERKUNG)
VALUES (7004, 5001, 3004, 20, 25.00, 'geliefert');

-- Annahme: LIEFERUNG 5002 von LIEFERANT 1002 (BauProfi AG - Baustoff)
INSERT INTO LIEFERPOSITION (LIEFERPOSITION_ID, LIEFERUNG_ID, ARTIKEL_ID, MENGE, EINZELPREIS, BEMERKUNG)
VALUES (7002, 5002, 3002, 200, 1.20, 'teilweise');
INSERT INTO LIEFERPOSITION (LIEFERPOSITION_ID, LIEFERUNG_ID, ARTIKEL_ID, MENGE, EINZELPREIS, BEMERKUNG)
VALUES (7005, 5002, 3005, 15, 45.00, 'teilweise');

-- Annahme: LIEFERUNG 5003 von LIEFERANT 1003 (FoodSupply KG - Lebensmittel)
INSERT INTO LIEFERPOSITION (LIEFERPOSITION_ID, LIEFERUNG_ID, ARTIKEL_ID, MENGE, EINZELPREIS, BEMERKUNG)
VALUES (7003, 5003, 3006, 2, 1200.00, 'bestellt');
INSERT INTO LIEFERPOSITION (LIEFERPOSITION_ID, LIEFERUNG_ID, ARTIKEL_ID, MENGE, EINZELPREIS, BEMERKUNG)
VALUES (7006, 5003, 3007, 10, 30.00, 'bestellt');

-- GEBAEUDE
INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (800, 'Verwaltungsgebäude Berlin', 'Berlin', 1);

INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (801, 'Werkstatt Berlin', 'Berlin', 1);

INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (802, 'Therapiezentrum Minden', 'Minden', 2);

INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (803, 'Logistikhalle Minden', 'Minden', 2);

INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (804, 'Nebengebäude Berlin', 'Berlin', 1);

INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (805, 'Zellenblock A Berlin', 'Berlin', 1);
INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (806, 'Zellenblock B Berlin', 'Berlin', 1);
INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (807, 'Infirmary Berlin', 'Berlin', 1);
INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (808, 'Besuchsgebäude Berlin', 'Berlin', 1);
INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (809, 'Zellenblock A Minden', 'Minden', 2);
INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (810, 'Werkstatt Minden', 'Minden', 2);
INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (811, 'Therapiezentrum Minden', 'Minden', 2); 

INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (812, 'Mensa Minden', 'Minden', 2); 
INSERT INTO GEBAEUDE (GEBAEUDE_ID, BEZEICHNUNG, STANDORT, STANDORT_ID)
VALUES (813, 'Mensa Berlin', 'Berlin', 1); 

-- RAUM
INSERT INTO RAUM (RAUM_ID, GEBAEUDE_ID, STANDORT_ID, RAUMNR, TYP)
VALUES (820, 805, 1, 'A-01', 'Zellenflur');
INSERT INTO RAUM (RAUM_ID, GEBAEUDE_ID, STANDORT_ID, RAUMNR, TYP)
VALUES (821, 805, 1, 'A-02', 'Einzelzelle');
INSERT INTO RAUM (RAUM_ID, GEBAEUDE_ID, STANDORT_ID, RAUMNR, TYP)
VALUES (822, 805, 1, 'A-03', 'Einzelzelle');
INSERT INTO RAUM (RAUM_ID, GEBAEUDE_ID, STANDORT_ID, RAUMNR, TYP)
VALUES (823, 806, 1, 'B-01', 'Zellenflur');
INSERT INTO RAUM (RAUM_ID, GEBAEUDE_ID, STANDORT_ID, RAUMNR, TYP)
VALUES (824, 806, 1, 'B-02', 'Mehrbettzelle');
INSERT INTO RAUM (RAUM_ID, GEBAEUDE_ID, STANDORT_ID, RAUMNR, TYP)
VALUES (825, 807, 2, 'INF-01', 'Behandlungsraum');
INSERT INTO RAUM (RAUM_ID, GEBAEUDE_ID, STANDORT_ID, RAUMNR, TYP)
VALUES (826, 808, 2, 'V-01', 'Besuchsraum');
INSERT INTO RAUM (RAUM_ID, GEBAEUDE_ID, STANDORT_ID, RAUMNR, TYP)
VALUES (827, 810, 2, 'W-01', 'Werkstatt');
INSERT INTO RAUM (RAUM_ID, GEBAEUDE_ID, STANDORT_ID, RAUMNR, TYP)
VALUES (828, 811, 2, 'T-01', 'Therapieraum');

-- ZELLE
INSERT INTO ZELLE (ZELLE_ID, GEBAEUDE_ID, MAX_BELEGUNG, SICHERHEITSSTUFE)
VALUES (830, 805, 1, 'hoch');
INSERT INTO ZELLE (ZELLE_ID, GEBAEUDE_ID, MAX_BELEGUNG, SICHERHEITSSTUFE)
VALUES (831, 806, 1, 'hoch');
INSERT INTO ZELLE (ZELLE_ID, GEBAEUDE_ID, MAX_BELEGUNG, SICHERHEITSSTUFE)
VALUES (832, 805, 2, 'mittel');
INSERT INTO ZELLE (ZELLE_ID, GEBAEUDE_ID, MAX_BELEGUNG, SICHERHEITSSTUFE)
VALUES (833, 809, 2, 'mittel');
INSERT INTO ZELLE (ZELLE_ID, GEBAEUDE_ID, MAX_BELEGUNG, SICHERHEITSSTUFE)
VALUES (834, 809, 2, 'niedrig');

-- GEFANGENER
INSERT INTO GEFANGENER (GEFANGENER_ID, PERSON_ID, EINTRITTSDATUM, ENTLASSUNGSDATUM, SICHERHEITSSTUFE)
VALUES (6001, 6, TO_DATE('2024-05-20','YYYY-MM-DD'), TO_TIMESTAMP('2025-05-20 08:00:00','YYYY-MM-DD HH24:MI:SS'), 'mittel');
INSERT INTO GEFANGENER (GEFANGENER_ID, PERSON_ID, EINTRITTSDATUM, ENTLASSUNGSDATUM, SICHERHEITSSTUFE)
VALUES (6002, 7, TO_DATE('2025-01-10','YYYY-MM-DD'), NULL, 'hoch');
INSERT INTO GEFANGENER (GEFANGENER_ID, PERSON_ID, EINTRITTSDATUM, ENTLASSUNGSDATUM, SICHERHEITSSTUFE)
VALUES (6003, 8, TO_DATE('2023-11-02','YYYY-MM-DD'), TO_TIMESTAMP('2024-11-02 12:00:00','YYYY-MM-DD HH24:MI:SS'), 'niedrig');
INSERT INTO GEFANGENER (GEFANGENER_ID, PERSON_ID, EINTRITTSDATUM, ENTLASSUNGSDATUM, SICHERHEITSSTUFE)
VALUES (6004, 9, TO_DATE('2022-08-15','YYYY-MM-DD'), NULL, 'mittel');
INSERT INTO GEFANGENER (GEFANGENER_ID, PERSON_ID, EINTRITTSDATUM, ENTLASSUNGSDATUM, SICHERHEITSSTUFE)
VALUES (6005, 10, TO_DATE('2021-03-10','YYYY-MM-DD'), NULL, 'hoch');

-- BELEGUNG
INSERT INTO BELEGUNG (BELEGUNG_ID, GEFANGENER_ID, ZELLE_ID, VON_DATUM, BIS_DATUM)
VALUES (6110, 6001, 830, TO_TIMESTAMP('2024-05-20 08:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-20 08:00:00','YYYY-MM-DD HH24:MI:SS'));

INSERT INTO BELEGUNG (BELEGUNG_ID, GEFANGENER_ID, ZELLE_ID, VON_DATUM, BIS_DATUM)
VALUES (6111, 6002, 831, TO_TIMESTAMP('2025-01-10 09:00:00','YYYY-MM-DD HH24:MI:SS'), NULL);

INSERT INTO BELEGUNG (BELEGUNG_ID, GEFANGENER_ID, ZELLE_ID, VON_DATUM, BIS_DATUM)
VALUES (6112, 6003, 832, TO_TIMESTAMP('2023-11-02 12:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-11-02 12:00:00','YYYY-MM-DD HH24:MI:SS'));

INSERT INTO BELEGUNG (BELEGUNG_ID, GEFANGENER_ID, ZELLE_ID, VON_DATUM, BIS_DATUM)
VALUES (6113, 6004, 832, TO_TIMESTAMP('2024-12-01 07:30:00','YYYY-MM-DD HH24:MI:SS'), NULL);

INSERT INTO BELEGUNG (BELEGUNG_ID, GEFANGENER_ID, ZELLE_ID, VON_DATUM, BIS_DATUM)
VALUES (6114, 6005, 833, TO_TIMESTAMP('2021-03-10 14:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-02-15 13:30:00','YYYY-MM-DD HH24:MI:SS'));

INSERT INTO BELEGUNG (BELEGUNG_ID, GEFANGENER_ID, ZELLE_ID, VON_DATUM, BIS_DATUM)
VALUES (6115, 6005, 834, TO_TIMESTAMP('2025-02-15 14:00:00','YYYY-MM-DD HH24:MI:SS'), NULL);

-- RISIKOKATEGORIE
INSERT INTO RISIKOKATEGORIE (RISIKOKATEGORIE_ID, BEZEICHNUNG, BESCHREIBUNG)
VALUES (9001, 'Fluchtgefahr', 'erhöhte Fluchtwahrscheinlichkeit');

INSERT INTO RISIKOKATEGORIE (RISIKOKATEGORIE_ID, BEZEICHNUNG, BESCHREIBUNG)
VALUES (9002, 'Gewaltpotenzial', 'potenziell gewalttätig');

INSERT INTO RISIKOKATEGORIE (RISIKOKATEGORIE_ID, BEZEICHNUNG, BESCHREIBUNG)
VALUES (9003, 'Suizidal', 'Selbstgefährdung möglich');

-- GEFANGENER_RISIKO
INSERT INTO GEFANGENER_RISIKO (GEFANGENER_RISIKO_ID, GEFANGENER_ID, RISIKOKATEGORIE_ID, GUELTIG_AB, GUELTIG_BIS)
VALUES (6301, 6001, 9001, TO_TIMESTAMP('2024-05-20 00:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-20 00:00:00','YYYY-MM-DD HH24:MI:SS'));

INSERT INTO GEFANGENER_RISIKO (GEFANGENER_RISIKO_ID, GEFANGENER_ID, RISIKOKATEGORIE_ID, GUELTIG_AB, GUELTIG_BIS)
VALUES (6302, 6002, 9002, TO_TIMESTAMP('2025-01-10 00:00:00','YYYY-MM-DD HH24:MI:SS'), NULL);

INSERT INTO GEFANGENER_RISIKO (GEFANGENER_RISIKO_ID, GEFANGENER_ID, RISIKOKATEGORIE_ID, GUELTIG_AB, GUELTIG_BIS)
VALUES (6303, 6003, 9001, TO_TIMESTAMP('2023-11-02 00:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-11-02 00:00:00','YYYY-MM-DD HH24:MI:SS'));

INSERT INTO GEFANGENER_RISIKO (GEFANGENER_RISIKO_ID, GEFANGENER_ID, RISIKOKATEGORIE_ID, GUELTIG_AB, GUELTIG_BIS)
VALUES (6304, 6004, 9003, TO_TIMESTAMP('2024-12-01 00:00:00','YYYY-MM-DD HH24:MI:SS'), NULL);

INSERT INTO GEFANGENER_RISIKO (GEFANGENER_RISIKO_ID, GEFANGENER_ID, RISIKOKATEGORIE_ID, GUELTIG_AB, GUELTIG_BIS)
VALUES (6305, 6005, 9002, TO_TIMESTAMP('2021-03-10 14:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-02-15 13:30:00','YYYY-MM-DD HH24:MI:SS'));

-- DELIKT
INSERT INTO DELIKT (DELIKT_ID, PARAGRAPH, BEZEICHNUNG, BESCHREIBUNG, MAX_STRAFE_MONATE)
VALUES (9501, '§242', 'Diebstahl', 'einfacher Diebstahl, fremde bewegliche Sache', 24);

INSERT INTO DELIKT (DELIKT_ID, PARAGRAPH, BEZEICHNUNG, BESCHREIBUNG, MAX_STRAFE_MONATE)
VALUES (9502, '§223', 'Körperverletzung', 'vorsätzliche Körperverletzung, leichte Verletzung', 60);

INSERT INTO DELIKT (DELIKT_ID, PARAGRAPH, BEZEICHNUNG, BESCHREIBUNG, MAX_STRAFE_MONATE)
VALUES (9503, '§263', 'Betrug', 'Vermögensschädigung durch Täuschung', 120);

INSERT INTO DELIKT (DELIKT_ID, PARAGRAPH, BEZEICHNUNG, BESCHREIBUNG, MAX_STRAFE_MONATE)
VALUES (9504, '§244', 'Raub', 'Diebstahl unter Anwendung von Gewalt oder Drohung', 180);

INSERT INTO DELIKT (DELIKT_ID, PARAGRAPH, BEZEICHNUNG, BESCHREIBUNG, MAX_STRAFE_MONATE)
VALUES (9505, '§315c', 'Gefährlicher Eingriff in den Straßenverkehr', 'riskantes Verhalten mit Gefährdung Dritter', 48);

-- VERURTEILUNG
INSERT INTO VERURTEILUNG (VERURTEILUNG_ID, GEFANGENER_ID, DELIKT_ID, URTEIL_DATUM, STRAFDAUER_MONATE, AKTENZEICHEN)
VALUES (9701, 6001, 9501, TO_DATE('2024-04-01','YYYY-MM-DD'), 12, 'AZ-2024-001');

INSERT INTO VERURTEILUNG (VERURTEILUNG_ID, GEFANGENER_ID, DELIKT_ID, URTEIL_DATUM, STRAFDAUER_MONATE, AKTENZEICHEN)
VALUES (9702, 6002, 9502, TO_DATE('2025-02-15','YYYY-MM-DD'), 24, 'AZ-2025-045');

INSERT INTO VERURTEILUNG (VERURTEILUNG_ID, GEFANGENER_ID, DELIKT_ID, URTEIL_DATUM, STRAFDAUER_MONATE, AKTENZEICHEN)
VALUES (9703, 6003, 9503, TO_DATE('2023-10-10','YYYY-MM-DD'), 36, 'AZ-2023-210');

INSERT INTO VERURTEILUNG (VERURTEILUNG_ID, GEFANGENER_ID, DELIKT_ID, URTEIL_DATUM, STRAFDAUER_MONATE, AKTENZEICHEN)
VALUES (9704, 6004, 9504, TO_DATE('2022-07-20','YYYY-MM-DD'), 60, 'AZ-2022-078');

INSERT INTO VERURTEILUNG (VERURTEILUNG_ID, GEFANGENER_ID, DELIKT_ID, URTEIL_DATUM, STRAFDAUER_MONATE, AKTENZEICHEN)
VALUES (9705, 6005, 9505, TO_DATE('2021-11-05','YYYY-MM-DD'), 18, 'AZ-2021-332');

-- BESUCHER
INSERT INTO BESUCHER (BESUCHER_ID, PERSON_ID, REGISTRIERT_AM, STRASSE, PLZ, ORT, BEMERKUNG)
VALUES (4201, 11, TO_TIMESTAMP('2025-10-05 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Königsallee 1', '40212', 'Düsseldorf', 'Angehörige');

INSERT INTO BESUCHER (BESUCHER_ID, PERSON_ID, REGISTRIERT_AM, STRASSE, PLZ, ORT)
VALUES (4202, 12, TO_TIMESTAMP('2025-11-12 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Leipziger Straße 2', '04109', 'Leipzig');

INSERT INTO BESUCHER (BESUCHER_ID, PERSON_ID, REGISTRIERT_AM, STRASSE, PLZ, ORT)
VALUES (4203, 13, TO_TIMESTAMP('2025-12-02 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Maximilianstraße 3', '80539', 'München');

INSERT INTO BESUCHER (BESUCHER_ID, PERSON_ID, REGISTRIERT_AM, STRASSE, PLZ, ORT)
VALUES (4204, 14, TO_TIMESTAMP('2025-09-01 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Domplatz 4', '39104', 'Magdeburg');

INSERT INTO BESUCHER (BESUCHER_ID, PERSON_ID, REGISTRIERT_AM, STRASSE, PLZ, ORT)
VALUES (4205, 15, TO_TIMESTAMP('2025-09-02 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Rathausmarkt 5', '20095', 'Hamburg');

INSERT INTO BESUCHER (BESUCHER_ID, PERSON_ID, REGISTRIERT_AM, STRASSE, PLZ, ORT)
VALUES (4206, 16, TO_TIMESTAMP('2025-09-03 15:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Theaterstraße 6', '26122', 'Oldenburg');

-- ANWALT
INSERT INTO ANWALT (ANWALT_ID, BESUCHER_ID, KANZLEI_NAME, KAMMER_NUMMER, TELEFON_KANZLEI, EMAIL_KANZLEI)
VALUES (4501, 4204, 'Kanzlei Recht und Partner', '98765', '+49-421-555123', 'kontakt@recht-partner.de');
INSERT INTO ANWALT (ANWALT_ID, BESUCHER_ID, KANZLEI_NAME, KAMMER_NUMMER, TELEFON_KANZLEI, EMAIL_KANZLEI)
VALUES (4502, 4205, 'Müller Legal', '54321', '+49-251-444200', 'kanzlei@muellerlegal.de');
INSERT INTO ANWALT (ANWALT_ID, BESUCHER_ID, KANZLEI_NAME, KAMMER_NUMMER, TELEFON_KANZLEI, EMAIL_KANZLEI)
VALUES (4503, 4206, 'Advokat und Kollegen', '12345', '+49-30-333900', 'info@advokat-kollegen.de');

-- GEFANGENER_ANWALT
INSERT INTO GEFANGENER_ANWALT (GEFANGENER_ANWALT_ID, GEFANGENER_ID, ANWALT_ID, MANDAT_AB, MANDAT_BIS)
VALUES (4801, 6001, 4501, TO_DATE('2025-10-10','YYYY-MM-DD'), TO_DATE('2026-10-09','YYYY-MM-DD'));

INSERT INTO GEFANGENER_ANWALT (GEFANGENER_ANWALT_ID, GEFANGENER_ID, ANWALT_ID, MANDAT_AB, MANDAT_BIS)
VALUES (4802, 6002, 4502, TO_DATE('2025-02-20','YYYY-MM-DD'), NULL);

INSERT INTO GEFANGENER_ANWALT (GEFANGENER_ANWALT_ID, GEFANGENER_ID, ANWALT_ID, MANDAT_AB, MANDAT_BIS)
VALUES (4803, 6003, 4503, TO_DATE('2024-01-15','YYYY-MM-DD'), TO_DATE('2024-12-31','YYYY-MM-DD'));

INSERT INTO GEFANGENER_ANWALT (GEFANGENER_ANWALT_ID, GEFANGENER_ID, ANWALT_ID, MANDAT_AB, MANDAT_BIS)
VALUES (4804, 6004, 4501, TO_DATE('2025-06-01','YYYY-MM-DD'), NULL);

INSERT INTO GEFANGENER_ANWALT (GEFANGENER_ANWALT_ID, GEFANGENER_ID, ANWALT_ID, MANDAT_AB, MANDAT_BIS)
VALUES (4805, 6005, 4502, TO_DATE('2023-11-01','YYYY-MM-DD'), TO_DATE('2024-11-01','YYYY-MM-DD'));

-- BESCHAEFTIGUNG
INSERT INTO BESCHAEFTIGUNG (BESCHAEFTIGUNG_ID, GEBAEUDE_ID, BEZEICHNUNG, BESCHREIBUNG)
VALUES (5201, 801, 'Werkstattarbeit', 'Metallverarbeitung und Instandhaltung');

INSERT INTO BESCHAEFTIGUNG (BESCHAEFTIGUNG_ID, GEBAEUDE_ID, BEZEICHNUNG, BESCHREIBUNG)
VALUES (5202, 813, 'Küchenhilfe', 'Kantinenbetrieb, Essensausgabe');

INSERT INTO BESCHAEFTIGUNG (BESCHAEFTIGUNG_ID, GEBAEUDE_ID, BEZEICHNUNG, BESCHREIBUNG)
VALUES (5203, 800, 'Hausdienst', 'Reinigung, Instandhaltung Gebäude');

INSERT INTO BESCHAEFTIGUNG (BESCHAEFTIGUNG_ID, GEBAEUDE_ID, BEZEICHNUNG, BESCHREIBUNG)
VALUES (5204, 800, 'Gartenarbeit', 'Außenanlagen, Grünpflege');

-- GEFANGENER_BESCHAEFTIGUNG
INSERT INTO GEFANGENER_BESCHAEFTIGUNG (GEFANGENER_BESCHAEFTIGUNG_ID, GEFANGENER_ID, BESCHAEFTIGUNG_ID, VON_DATUM, BIS_DATUM)
VALUES (5410, 6001, 5201, TO_DATE('2024-06-01','YYYY-MM-DD'), NULL);

INSERT INTO GEFANGENER_BESCHAEFTIGUNG (GEFANGENER_BESCHAEFTIGUNG_ID, GEFANGENER_ID, BESCHAEFTIGUNG_ID, VON_DATUM, BIS_DATUM)
VALUES (5411, 6002, 5202, TO_DATE('2025-02-01','YYYY-MM-DD'), NULL);

INSERT INTO GEFANGENER_BESCHAEFTIGUNG (GEFANGENER_BESCHAEFTIGUNG_ID, GEFANGENER_ID, BESCHAEFTIGUNG_ID, VON_DATUM, BIS_DATUM)
VALUES (5412, 6003, 5203, TO_DATE('2024-01-15','YYYY-MM-DD'), NULL);

INSERT INTO GEFANGENER_BESCHAEFTIGUNG (GEFANGENER_BESCHAEFTIGUNG_ID, GEFANGENER_ID, BESCHAEFTIGUNG_ID, VON_DATUM, BIS_DATUM)
VALUES (5413, 6004, 5204, TO_DATE('2025-03-01','YYYY-MM-DD'), NULL);

INSERT INTO GEFANGENER_BESCHAEFTIGUNG (GEFANGENER_BESCHAEFTIGUNG_ID, GEFANGENER_ID, BESCHAEFTIGUNG_ID, VON_DATUM, BIS_DATUM)
VALUES (5414, 6005, 5201, TO_DATE('2025-02-01','YYYY-MM-DD'), NULL);

-- THERAPIEART
INSERT INTO THERAPIEART (THERAPIEART_ID, BEZEICHNUNG, STANDARD_DAUER_MIN, BESCHREIBUNG)
VALUES (7101, 'Einzeltherapie', 60, 'Psychologische Einzelstunde, individuelles Setting');

INSERT INTO THERAPIEART (THERAPIEART_ID, BEZEICHNUNG, STANDARD_DAUER_MIN, BESCHREIBUNG)
VALUES (7102, 'Gruppentherapie', 90, 'Therapie in Kleingruppen, Fokus auf Interaktion');

INSERT INTO THERAPIEART (THERAPIEART_ID, BEZEICHNUNG, STANDARD_DAUER_MIN, BESCHREIBUNG)
VALUES (7103, 'Ergotherapie', 45, 'Funktionelle Therapie zur Alltagsbewältigung und Motorik');

INSERT INTO THERAPIEART (THERAPIEART_ID, BEZEICHNUNG, STANDARD_DAUER_MIN, BESCHREIBUNG)
VALUES (7104, 'Sporttherapie', 60, 'Bewegungsorientierte Therapie zur Stabilisierung und Prävention');

INSERT INTO THERAPIEART (THERAPIEART_ID, BEZEICHNUNG, STANDARD_DAUER_MIN, BESCHREIBUNG)
VALUES (7105, 'Suchttherapie', 60, 'Strukturierte Therapieprogramme für Abhängigkeitserkrankungen');

INSERT INTO THERAPIEART (THERAPIEART_ID, BEZEICHNUNG, STANDARD_DAUER_MIN, BESCHREIBUNG)
VALUES (7106, 'Kunsttherapie', 50, 'Kreative Therapie zur emotionalen Verarbeitung');

-- THERAPIE (Sitzungen)
INSERT INTO THERAPIE (THERAPIE_ID, THERAPIEART_ID, GEFANGENER_ID, DATUM, DAUER_MIN, BEMERKUNG)
VALUES (7201, 7101, 6001, TO_TIMESTAMP('2025-11-20 10:00:00','YYYY-MM-DD HH24:MI:SS'), 60, 'Erstgespräch, Einzeltherapie');

INSERT INTO THERAPIE (THERAPIE_ID, THERAPIEART_ID, GEFANGENER_ID, DATUM, DAUER_MIN, BEMERKUNG)
VALUES (7202, 7103, 6001, TO_TIMESTAMP('2025-11-27 10:00:00','YYYY-MM-DD HH24:MI:SS'), 45, 'Ergotherapie, Folge');

INSERT INTO THERAPIE (THERAPIE_ID, THERAPIEART_ID, GEFANGENER_ID, DATUM, DAUER_MIN, BEMERKUNG)
VALUES (7203, 7102, 6002, TO_TIMESTAMP('2025-11-21 14:00:00','YYYY-MM-DD HH24:MI:SS'), 90, 'Gruppentherapie, Integration');

INSERT INTO THERAPIE (THERAPIE_ID, THERAPIEART_ID, GEFANGENER_ID, DATUM, DAUER_MIN, BEMERKUNG)
VALUES (7204, 7101, 6003, TO_TIMESTAMP('2025-11-22 09:30:00','YYYY-MM-DD HH24:MI:SS'), 60, 'Einzeltherapie, Stabilisierung');

INSERT INTO THERAPIE (THERAPIE_ID, THERAPIEART_ID, GEFANGENER_ID, DATUM, DAUER_MIN, BEMERKUNG)
VALUES (7205, 7105, 6003, TO_TIMESTAMP('2025-11-29 09:30:00','YYYY-MM-DD HH24:MI:SS'), 60, 'Suchttherapie, Modul 1');

INSERT INTO THERAPIE (THERAPIE_ID, THERAPIEART_ID, GEFANGENER_ID, DATUM, DAUER_MIN, BEMERKUNG)
VALUES (7206, 7104, 6004, TO_TIMESTAMP('2025-11-23 11:00:00','YYYY-MM-DD HH24:MI:SS'), 60, 'Sporttherapie, Aktivierung');

INSERT INTO THERAPIE (THERAPIE_ID, THERAPIEART_ID, GEFANGENER_ID, DATUM, DAUER_MIN, BEMERKUNG)
VALUES (7207, 7106, 6005, TO_TIMESTAMP('2025-11-24 13:00:00','YYYY-MM-DD HH24:MI:SS'), 50, 'Kunsttherapie, Ausdrucksarbeit');

-- AUSBILDUNG
INSERT INTO AUSBILDUNG (AUSBILDUNG_ID, PERSON_ID, BEZEICHNUNG, BETRIEB_NAME, ORT, BEGINN_DATUM, ENDE_DATUM, ABSCHLUSSART, BEMERKUNG)
VALUES (3311, 6, 'Ausbildung zum Justizvollzugsbeamten', 'JVA Berlin Ausbildungszentrum', 'Berlin',
TO_DATE('2021-09-01', 'YYYY-MM-DD'), TO_DATE('2024-08-31', 'YYYY-MM-DD'), 'Beamtenlaufbahn mittlerer Dienst', 'Grundausbildung Vollzug');

INSERT INTO AUSBILDUNG (AUSBILDUNG_ID, PERSON_ID, BEZEICHNUNG, BETRIEB_NAME, ORT, BEGINN_DATUM, ENDE_DATUM, ABSCHLUSSART)
VALUES (3312, 7, 'Verwaltungsausbildung im Justizvollzug', 'JVA Minden Verwaltung', 'Minden',
TO_DATE('2020-09-01', 'YYYY-MM-DD'), TO_DATE('2023-08-31', 'YYYY-MM-DD'), 'Beamtenlaufbahn gehobener Dienst');

INSERT INTO AUSBILDUNG (AUSBILDUNG_ID, PERSON_ID, BEZEICHNUNG, BETRIEB_NAME, ORT, BEGINN_DATUM, ENDE_DATUM, ABSCHLUSSART, BEMERKUNG)
VALUES (3313, 8, 'Fortbildung Sicherheits- und Einsatztraining', 'JVA Köln', 'Köln',
TO_DATE('2024-01-15', 'YYYY-MM-DD'), TO_DATE('2024-06-15', 'YYYY-MM-DD'), 'Zertifikat', 'Spezialtraining für Vollzugsdienst');

INSERT INTO AUSBILDUNG (AUSBILDUNG_ID, PERSON_ID, BEZEICHNUNG, BETRIEB_NAME, ORT, BEGINN_DATUM, ENDE_DATUM, ABSCHLUSSART)
VALUES (3314, 9, 'Ausbildung Sozialdienst im Vollzug', 'JVA Oldenburg', 'Oldenburg',
TO_DATE('2019-10-01', 'YYYY-MM-DD'), TO_DATE('2022-09-30', 'YYYY-MM-DD'), 'staatlich anerkannt');

INSERT INTO AUSBILDUNG (AUSBILDUNG_ID, PERSON_ID, BEZEICHNUNG, BETRIEB_NAME, ORT, BEGINN_DATUM, ENDE_DATUM, ABSCHLUSSART, BEMERKUNG)
VALUES (3315, 10, 'Technische Ausbildung Gebäudemanagement JVA', 'JVA Freiburg Technikabteilung', 'Freiburg',
TO_DATE('2022-03-01', 'YYYY-MM-DD'), TO_DATE('2025-02-28', 'YYYY-MM-DD'), 'IHK-Abschluss', 'Schwerpunkt Haustechnik und Sicherheitssysteme');

COMMIT;