CREATE SEQUENCE PERSON_SEQ START WITH 17 INCREMENT BY 1;

CREATE SEQUENCE Besucher_SEQ START WITH 4207 INCREMENT BY 1;

CREATE SEQUENCE ANGESTELLTER_SEQ START WITH 4106 INCREMENT BY 1;

SELECT EMAIL, PASSWORT FROM PERSON, BESUCHER WHERE PERSON.PERSON_ID = BESUCHER.PERSON_ID;

SELECT * FROM GEFANGENER;