CREATE TABLE BESUCHER_VALIDIERUNG (
    BESUCHER_ID      NUMBER(10) NOT NULL,
    GEFANGENER_ID    NUMBER(10) NOT NULL,
    VALIDIERT        NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_BESUCHER_VALIDIERUNG
        PRIMARY KEY (BESUCHER_ID, GEFANGENER_ID),

    CONSTRAINT FK_BV_BESUCHER
        FOREIGN KEY (BESUCHER_ID)
        REFERENCES BESUCHER (BESUCHER_ID),

    CONSTRAINT FK_BV_GEFANGENER
        FOREIGN KEY (GEFANGENER_ID)
        REFERENCES GEFANGENER (GEFANGENER_ID),

    CONSTRAINT CK_BV_VALIDIERT
        CHECK (VALIDIERT IN (0,1))
);

CREATE INDEX IDX_BV_GEFANGENER
ON BESUCHER_VALIDIERUNG (GEFANGENER_ID);