CREATE TABLE GEFANGENEN_SLOTS (
    SLOT_ID       NUMBER(10)    NOT NULL,
    GEFANGENER_ID NUMBER(10)    NOT NULL,
    WOCHENTAG     NUMBER(1)     NOT NULL, -- 1 = Montag, 2 = Dienstag, ..., 5 = Freitag
    UHRZEIT       VARCHAR2(5)   NOT NULL, -- Format: '10:00', '14:30'
    
    CONSTRAINT PK_GEFANGENEN_SLOTS PRIMARY KEY (SLOT_ID),
    CONSTRAINT FK_GS_GEFANGENER FOREIGN KEY (GEFANGENER_ID) REFERENCES GEFANGENER(GEFANGENER_ID),
    CONSTRAINT CK_GS_WOCHENTAG CHECK (WOCHENTAG BETWEEN 1 AND 5)
);

-- Sequence für die IDs erstellen
CREATE SEQUENCE GEFANGENEN_SLOTS_SEQ START WITH 1 INCREMENT BY 1;

-- Besuchszeiten für Gefangener 6001 (Montag 09:00 und Mittwoch 13:00)
INSERT INTO GEFANGENEN_SLOTS (SLOT_ID, GEFANGENER_ID, WOCHENTAG, UHRZEIT) 
VALUES (GEFANGENEN_SLOTS_SEQ.nextval, 6001, 1, '09:00');
INSERT INTO GEFANGENEN_SLOTS (SLOT_ID, GEFANGENER_ID, WOCHENTAG, UHRZEIT) 
VALUES (GEFANGENEN_SLOTS_SEQ.nextval, 6001, 3, '13:00');

-- Besuchszeiten für Gefangener 6002 (Dienstag 10:30 und Donnerstag 14:30)
INSERT INTO GEFANGENEN_SLOTS (SLOT_ID, GEFANGENER_ID, WOCHENTAG, UHRZEIT) 
VALUES (GEFANGENEN_SLOTS_SEQ.nextval, 6002, 2, '10:30');
INSERT INTO GEFANGENEN_SLOTS (SLOT_ID, GEFANGENER_ID, WOCHENTAG, UHRZEIT) 
VALUES (GEFANGENEN_SLOTS_SEQ.nextval, 6002, 4, '14:30');

-- Besuchszeiten für Gefangener 6003 (Mittwoch 09:00 und Freitag 11:00)
INSERT INTO GEFANGENEN_SLOTS (SLOT_ID, GEFANGENER_ID, WOCHENTAG, UHRZEIT) 
VALUES (GEFANGENEN_SLOTS_SEQ.nextval, 6003, 3, '09:00');
INSERT INTO GEFANGENEN_SLOTS (SLOT_ID, GEFANGENER_ID, WOCHENTAG, UHRZEIT) 
VALUES (GEFANGENEN_SLOTS_SEQ.nextval, 6003, 5, '11:00');

-- Besuchszeiten für Gefangener 6004 (Donnerstag 10:00 und Freitag 15:00)
INSERT INTO GEFANGENEN_SLOTS (SLOT_ID, GEFANGENER_ID, WOCHENTAG, UHRZEIT) 
VALUES (GEFANGENEN_SLOTS_SEQ.nextval, 6004, 4, '10:00');
INSERT INTO GEFANGENEN_SLOTS (SLOT_ID, GEFANGENER_ID, WOCHENTAG, UHRZEIT) 
VALUES (GEFANGENEN_SLOTS_SEQ.nextval, 6004, 5, '15:00');

-- Besuchszeiten für Gefangener 6005 (Montag 14:00 und Dienstag 13:30)
INSERT INTO GEFANGENEN_SLOTS (SLOT_ID, GEFANGENER_ID, WOCHENTAG, UHRZEIT) 
VALUES (GEFANGENEN_SLOTS_SEQ.nextval, 6005, 1, '14:00');
INSERT INTO GEFANGENEN_SLOTS (SLOT_ID, GEFANGENER_ID, WOCHENTAG, UHRZEIT) 
VALUES (GEFANGENEN_SLOTS_SEQ.nextval, 6005, 2, '13:30');

-- Wichtig: Speichern der Daten in Oracle
COMMIT;

